runtime: php74

handlers:
- url: /(.*\.(gif|png|jpg|jpeg|svg|css|js|ttf|woff|woff2|xlsx))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|jpeg|svg|css|js|ttf|woff|woff|xlsx)$

env_variables:
  APP_URL: "https://b21-cap0035.et.r.appspot.com"
  APP_DEBUG: true
  APP_TIMEZONE: "UTC"
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
  DB_CONNECTION: "mysql"
  DB_PORT: 3306
  DB_DATABASE: "sehatmentalku"
  DB_USERNAME: "root"
  DB_SOCKET: "/cloudsql/b21-cap0035:asia-southeast2:sehatmentalku"
  DB_PASSWORD: "u49kzHmvHx7LDkBm"
  FILESYSTEM_DRIVER: gcs
  GOOGLE_CLOUD_PROJECT_ID: b21-cap0035
  GOOGLE_CLOUD_STORAGE_BUCKET: b21-cap0035.appspot.com
  JWT_SECRET: SPTn2NIfc029tpJX6MMN9rnsEl3WCB4I7g6VVTYTshRjShl2cREnEJ8yzQxNilrO