runtime: php74

handlers:
- url: /(.*\.(gif|png|jpg|jpeg|svg|css|js|ttf|woff|woff2|xlsx))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|jpeg|svg|css|js|ttf|woff|woff|xlsx)$

env_variables:
  APP_URL: "https://sehat-mentalku.et.r.appspot.com"
  APP_DEBUG: true
  APP_TIMEZONE: "UTC"
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
  DB_CONNECTION: "mysql"
  DB_PORT: 3306
  DB_DATABASE: "sehatmentalku"
  DB_USERNAME: "root"
  DB_SOCKET: "/cloudsql/sehat-mentalku:asia-southeast2:sehat-mentalku-db"
  DB_PASSWORD: "vdhN10kHr0EAdzkB"
  FILESYSTEM_DRIVER: gcs
  GOOGLE_CLOUD_PROJECT_ID: sehat-mentalku
  GOOGLE_CLOUD_STORAGE_BUCKET: sehat-mentalku-bucket
  JWT_SECRET: SPTn2NIfc029tpJX6MMN9rnsEl3WCB4I7g6VVTYTshRjShl2cREnEJ8yzQxNilrO